swagger: '2.0'
info:
  version: v1
  title: Pet Store API
paths:
  /api/Pet:
    get:
      tags:
        - Pet
      summary: Gets the pets.
      operationId: GetPets
      consumes: []
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/PetViewModel'
        default:
          description: Default Error Response
          schema:
            $ref: '#/definitions/ProblemDetails'
    post:
      tags:
        - Pet
      summary: Posts the pet.
      operationId: PostPet
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: pet
          in: body
          description: The pet.
          required: false
          schema:
            $ref: '#/definitions/PetViewModel'
      responses:
        '201':
          description: Success
          schema:
            $ref: '#/definitions/PetViewModel'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ProblemDetails'
        default:
          description: Default Error Response
          schema:
            $ref: '#/definitions/ProblemDetails'
  '/api/Pet/{id}':
    get:
      tags:
        - Pet
      summary: Gets the pet.
      operationId: GetPet
      consumes: []
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: The identifier.
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/PetViewModel'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ProblemDetails'
        default:
          description: Default Error Response
          schema:
            $ref: '#/definitions/ProblemDetails'
    put:
      tags:
        - Pet
      summary: Puts the pet.
      operationId: PutPet
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: The identifier.
          required: true
          type: integer
          format: int32
        - name: pet
          in: body
          description: The pet.
          required: false
          schema:
            $ref: '#/definitions/PetViewModel'
      responses:
        '204':
          description: Success
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ProblemDetails'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ProblemDetails'
        default:
          description: Default Error Response
          schema:
            $ref: '#/definitions/ProblemDetails'
    delete:
      tags:
        - Pet
      summary: Deletes the pet.
      operationId: DeletePet
      consumes: []
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: The identifier.
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/PetViewModel'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ProblemDetails'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ProblemDetails'
        default:
          description: Default Error Response
          schema:
            $ref: '#/definitions/ProblemDetails'
definitions:
  PetViewModel:
    required:
      - name
    type: object
    properties:
      id:
        format: int32
        type: integer
      name:
        type: string
      status:
        enum:
          - Available
          - Pending
          - Sold
        type: string
      dateOfBirth:
        format: date
        type: string
      registrationTimestamp:
        format: date-time
        type: string
      petType:
        type: string
  ProblemDetails:
    type: object
    properties:
      type:
        type: string
      title:
        type: string
      status:
        format: int32
        type: integer
      detail:
        type: string
      instance:
        type: string
    additionalProperties:
      type: object
