// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetStore.Core;
using PetStore.DataAccess;

namespace PetStore.DataAccess.Migrations
{
    [DbContext(typeof(PetStoreDbContext))]
    [Migration("20190411004736_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PetStore.Core.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("DATE");

                    b.Property<string>("Name");

                    b.Property<string>("PetType")
                        .IsRequired();

                    b.Property<DateTime>("RegistrationTimestamp");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasDiscriminator<string>("PetType").HasValue("Pet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2016, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sadie",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 421, DateTimeKind.Local).AddTicks(3187),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2015, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sophie",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(623),
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2017, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Simba",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(678),
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2016, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jasper",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(683),
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2017, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sir Snuggles of Fluffington",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(686),
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2015, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sassafrass",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(693),
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(2015, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Luna",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(696),
                            Status = 2
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(2016, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Buddy",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(700),
                            Status = 2
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2015, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mooncake",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(703),
                            Status = 2
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(2015, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Judas Stardust",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(707),
                            Status = 2
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(2016, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bentley",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(711),
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(2016, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bella",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(714),
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(2017, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lucy",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(718),
                            Status = 2
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(2017, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maggie",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(721),
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(2016, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sugar Britches",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(725),
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(2017, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nala",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(728),
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(2015, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lola",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(732),
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(2016, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Milo",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(736),
                            Status = 2
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(2017, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bella",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(739),
                            Status = 0
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(2016, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Emoji",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(743),
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            DateOfBirth = new DateTime(2015, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lucy",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(746),
                            Status = 1
                        },
                        new
                        {
                            Id = 22,
                            DateOfBirth = new DateTime(2016, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Daisy",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(749),
                            Status = 0
                        },
                        new
                        {
                            Id = 23,
                            DateOfBirth = new DateTime(2016, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Neil Catrick Harris",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(753),
                            Status = 0
                        },
                        new
                        {
                            Id = 24,
                            DateOfBirth = new DateTime(2015, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Charlie",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(756),
                            Status = 1
                        },
                        new
                        {
                            Id = 25,
                            DateOfBirth = new DateTime(2015, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Smokey",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(760),
                            Status = 0
                        },
                        new
                        {
                            Id = 26,
                            DateOfBirth = new DateTime(2017, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Oliver",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(763),
                            Status = 2
                        },
                        new
                        {
                            Id = 27,
                            DateOfBirth = new DateTime(2016, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rocky",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(766),
                            Status = 0
                        },
                        new
                        {
                            Id = 28,
                            DateOfBirth = new DateTime(2016, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Luna",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(770),
                            Status = 0
                        },
                        new
                        {
                            Id = 29,
                            DateOfBirth = new DateTime(2016, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lily",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(773),
                            Status = 2
                        },
                        new
                        {
                            Id = 30,
                            DateOfBirth = new DateTime(2015, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chloe",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(777),
                            Status = 2
                        },
                        new
                        {
                            Id = 31,
                            DateOfBirth = new DateTime(2017, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Loki",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(780),
                            Status = 0
                        },
                        new
                        {
                            Id = 32,
                            DateOfBirth = new DateTime(2016, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Leo",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(784),
                            Status = 2
                        },
                        new
                        {
                            Id = 33,
                            DateOfBirth = new DateTime(2016, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sir Leonardo ScraggleBottoms III",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(787),
                            Status = 0
                        },
                        new
                        {
                            Id = 34,
                            DateOfBirth = new DateTime(2016, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Charlie",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(791),
                            Status = 0
                        },
                        new
                        {
                            Id = 35,
                            DateOfBirth = new DateTime(2016, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mia",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(794),
                            Status = 0
                        },
                        new
                        {
                            Id = 36,
                            DateOfBirth = new DateTime(2017, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Max",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(797),
                            Status = 1
                        },
                        new
                        {
                            Id = 37,
                            DateOfBirth = new DateTime(2016, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Professor McGonagall",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(801),
                            Status = 2
                        },
                        new
                        {
                            Id = 38,
                            DateOfBirth = new DateTime(2016, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Oliver",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(804),
                            Status = 0
                        },
                        new
                        {
                            Id = 39,
                            DateOfBirth = new DateTime(2016, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cooper",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(807),
                            Status = 1
                        },
                        new
                        {
                            Id = 40,
                            DateOfBirth = new DateTime(2016, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Max",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(811),
                            Status = 2
                        },
                        new
                        {
                            Id = 41,
                            DateOfBirth = new DateTime(2015, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Molly",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(814),
                            Status = 1
                        },
                        new
                        {
                            Id = 42,
                            DateOfBirth = new DateTime(2015, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Teddy",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(818),
                            Status = 0
                        },
                        new
                        {
                            Id = 43,
                            DateOfBirth = new DateTime(2015, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Peppurrcorn VonPuskins",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(821),
                            Status = 1
                        },
                        new
                        {
                            Id = 44,
                            DateOfBirth = new DateTime(2015, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jack",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(825),
                            Status = 1
                        },
                        new
                        {
                            Id = 45,
                            DateOfBirth = new DateTime(2015, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Daisy",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(829),
                            Status = 2
                        },
                        new
                        {
                            Id = 46,
                            DateOfBirth = new DateTime(2016, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tucker",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(832),
                            Status = 2
                        },
                        new
                        {
                            Id = 47,
                            DateOfBirth = new DateTime(2015, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lola",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(835),
                            Status = 1
                        },
                        new
                        {
                            Id = 48,
                            DateOfBirth = new DateTime(2017, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chloe",
                            PetType = "Cat",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(839),
                            Status = 1
                        },
                        new
                        {
                            Id = 49,
                            DateOfBirth = new DateTime(2015, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Milo",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(842),
                            Status = 1
                        },
                        new
                        {
                            Id = 50,
                            DateOfBirth = new DateTime(2017, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Stella",
                            PetType = "Dog",
                            RegistrationTimestamp = new DateTime(2019, 4, 10, 20, 47, 36, 423, DateTimeKind.Local).AddTicks(845),
                            Status = 2
                        });
                });

            modelBuilder.Entity("PetStore.Core.Cat", b =>
                {
                    b.HasBaseType("PetStore.Core.Pet");

                    b.Property<double?>("WhiskersLength");

                    b.HasDiscriminator().HasValue("Cat");
                });

            modelBuilder.Entity("PetStore.Core.Dog", b =>
                {
                    b.HasBaseType("PetStore.Core.Pet");

                    b.Property<int?>("PackSize");

                    b.HasDiscriminator().HasValue("Dog");
                });
#pragma warning restore 612, 618
        }
    }
}
